services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp

  webapp:
    image: your-webapp-image:latest
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000" # Only exposed to nginx, not to the host

volumes:
  nginx_conf:
